### PR TITLE
Add full list of modes and programs

### PR DESCRIPTION
**Pull request by sebbegg**

### CODE REVIEW

**Comment by Kali-** [comment]
i suspect some heating.dhw.operating.modes.* are missing

**Comment by sebbegg** [comment]
Hm, but those values actually belong to a different enum set.

The two I implemented were only tested/intended for 
* heating.circuits.N.operating.modes.active
* heating.circuits.N.operating.programs.active
since that's what my device exposes.

The code only looks at the "operating.modes.active" suffix, so I guess that's why in your case those two get mixed up.
The DHW features would probably need a distinct set of enum values, since dhw & heating circuits have different sets string values.
In `get_metric_for_name` we'd have to add another if/else branch to pick the proper enum labels for the dhw operating modes.

Given the relatively large number of enum values, I wonder whether it would be sensible (and a little more "future proof" to use prometheus Info metrics, rather than enums)...

**Comment by sebbegg** [comment]
Hi @Kali- I've made quite a few changes.
For the dhw operating modes there's now a separate enum.

There's also a script in `tests` that fetches all data once from the Viessmann API and writes them (anonymized) to the test data folder.
If you like, feel free to run this and it - so the tests in the future can cover more variants.

**Comment by Kali-** [comment]
built, installed and switched off (dhw), set holiday and other mode everything looks fine

**Comment by sebbegg** [comment]
Again looking into the data... it appears that for every enum value of e.g. the heating circuits there is one dedicated metric, e.g. there in https://github.com/sebbegg/vicare-exporter/blob/add-modes-and-programs/tests/data/z62kZQ_device_2.json

```
heating.circuits.0.operating.programs.active
heating.circuits.0.operating.programs.comfort
heating.circuits.0.operating.programs.eco
heating.circuits.0.operating.programs.external
heating.circuits.0.operating.programs.holiday
heating.circuits.0.operating.programs.normal
heating.circuits.0.operating.programs.reduced
heating.circuits.0.operating.programs.standby
``` 

Would you be able to check what that list looks like in your case?
That might be a way to fetch the enum values dynamically upon start - and matching them to the individual installation.

**Comment by Kali-** [comment]
#grep heating.circuits.0.operating.programs data/3yXA7A_device_1.json | awk -F\" '{ print $4}'
heating.circuits.0.operating.programs.noDemand
heating.circuits.0.operating.programs.summerEco
heating.circuits.0.operating.programs.active
heating.circuits.0.operating.programs.comfort
heating.circuits.0.operating.programs.comfortEnergySaving
heating.circuits.0.operating.programs.forcedLastFromSchedule
heating.circuits.0.operating.programs.normal
heating.circuits.0.operating.programs.normalEnergySaving
heating.circuits.0.operating.programs.reduced
heating.circuits.0.operating.programs.reducedEnergySaving
heating.circuits.0.operating.programs.standby

**Comment by sebbegg** [comment]
Thanks - I'll merge this as-is, but will have a look to make this more flexible.

**Pull request merged**
